// Spaced-repetition cards. `module` controls when a card unlocks: it joins your review
// deck once you've started that module.
export type Card = { id: string; module: string; front: string; back: string }

const c = (module: string, front: string, back: string): Card => ({ id: `${module}:${front}`, module, front, back })

export const cards: Card[] = [
  c('t1-1.1', 'Token', 'The unit a model reads and writes: a word piece produced by the tokenizer (BPE). Cost and context limits are counted in tokens.'),
  c('t1-1.1', 'Logits', 'Raw, unnormalised scores the model outputs for every token in the vocabulary before softmax.'),
  c('t1-1.1', 'Temperature', 'Divides the logits before softmax. Low = sharper, more deterministic; high = flatter, more random.'),
  c('t1-1.1', 'Top-p (nucleus) sampling', 'Sample only from the smallest set of tokens whose probabilities add up to p.'),
  c('t1-1.1', 'Context window', 'The maximum number of tokens (input + output) the model can attend to in one call.'),
  c('t1-1.2', 'Prompt caching', 'Reusing the provider-side processed prefix of a prompt across calls, cutting cost and latency for repeated context.'),
  c('t1-1.2', 'Tool use / function calling', 'The model emits a structured request to call a function you define; your code runs it and returns the result.'),
  c('t1-1.3', 'Few-shot prompting', 'Including worked input→output examples in the prompt to show the model the task format.'),
  c('t1-1.3', 'Context engineering', 'Deciding which information enters the context window, in what form and order, so the model can do the task.'),
  c('t1-1.4', 'Embedding', 'A dense vector representing meaning; similar texts end up close together (high cosine similarity).'),
  c('t1-1.4', 'BM25', 'A classic keyword ranking function based on term frequency and inverse document frequency, with length normalisation.'),
  c('t1-1.4', 'Hybrid search', 'Combining keyword (BM25) and vector retrieval, often merged with reciprocal rank fusion.'),
  c('t1-1.4', 'Reranker', 'A slower, more accurate model (often a cross-encoder) that reorders a shortlist of retrieved candidates.'),
  c('t1-1.4', 'HNSW', 'Hierarchical Navigable Small World: a graph-based approximate nearest-neighbour index used by vector stores like pgvector.'),
  c('t1-1.4', 'recall@k', 'The fraction of queries where at least one relevant item appears in the top k results.'),
  c('t1-1.5', 'Agent loop', 'Model → tool call → tool result → model … until the model produces a final answer or hits the step limit.'),
  c('t1-1.5', 'MCP', 'Model Context Protocol: an open standard for exposing tools, resources and prompts to AI clients through servers.'),
  c('t1-1.5', 'Orchestrator–workers', 'A pattern where a lead model breaks a task down and delegates subtasks to worker models, then combines the results.'),
  c('t1-1.6', 'Error analysis', 'Reading real traces, noting failures and grouping them into categories to decide what to measure and fix.'),
  c('t1-1.6', 'LLM-as-judge', 'Using a model to grade outputs against a rubric. It must be validated against human labels.'),
  c('t1-1.7', 'Prompt injection', 'Untrusted text (from a user, document, web page or tool output) containing instructions that hijack the model.'),
  c('t1-1.7', 'Lethal trifecta', 'Private data access + untrusted content + an exfiltration channel. Together they let injections steal data.'),
  c('t1-1.8', 'Durable execution', 'Workflow state is persisted (e.g. Temporal), so long multi-step processes survive crashes and resume.'),
  c('t1-1.8', 'Human-in-the-loop interrupt', 'Pausing an agent graph or workflow until a person approves, edits or rejects a proposed action.'),

  c('t2-2.1', 'Broadcasting', 'Automatic expansion of size-1 dimensions so tensors of different shapes can be combined elementwise.'),
  c('t2-2.1', 'Autograd', 'PyTorch records operations on tensors and computes gradients automatically with .backward().'),
  c('t2-2.2', 'Backpropagation', 'Computing gradients by applying the chain rule backwards through the computation graph.'),
  c('t2-2.2', 'Chain rule', 'd/dx f(g(x)) = f′(g(x)) · g′(x). Upstream gradient × local gradient.'),
  c('t2-2.3', 'Overfitting', 'Low training loss but high validation loss: the model memorises instead of generalising.'),
  c('t2-2.3', 'Residual connection', 'y = x + f(x). It gives gradients a direct path and makes deep nets trainable.'),
  c('t2-2.3', 'LayerNorm / RMSNorm', 'Normalise each token\'s activation vector. RMSNorm skips mean-centring and is cheaper.'),
  c('t2-2.3', 'Weight decay', 'Shrinking weights towards zero each step (decoupled in AdamW) to regularise.'),
  c('t2-2.4', 'Self-attention', 'softmax(QKᵀ/√d)·V. Each token mixes information from other tokens, weighted by relevance.'),
  c('t2-2.4', 'Causal mask', 'Sets attention scores to future positions to −∞ so tokens only attend to the past.'),
  c('t2-2.4', 'KV cache', 'Stored keys and values of previous tokens, so each decode step only computes the new token.'),
  c('t2-2.4', 'RoPE', 'Rotary positional embeddings: encode position by rotating Q and K vectors, so attention depends on relative position.'),
  c('t2-2.4', 'BPE', 'Byte Pair Encoding: build a vocabulary by repeatedly merging the most frequent adjacent symbol pairs.'),
  c('t2-2.4', 'Perplexity', 'exp(average cross-entropy per token). Lower means the model is less "surprised" by the text.'),
  c('t2-2.5', 'LoRA', 'Freeze W; train a low-rank update ΔW = B·A (rank r ≪ d). Few trainable parameters, mergeable after training.'),
  c('t2-2.5', 'QLoRA', 'LoRA on top of a 4-bit (NF4) quantised frozen base model, so large models fine-tune on one GPU.'),
  c('t2-2.5', 'DPO', 'Direct Preference Optimization: train on chosen/rejected pairs with a closed-form loss, with no reward model or RL loop.'),
  c('t2-2.5', 'SFT', 'Supervised fine-tuning on input→ideal output pairs (instruction data).'),
  c('t2-2.6', 'Arithmetic intensity', 'FLOPs per byte of memory moved. Low = memory-bound; high = compute-bound.'),
  c('t2-2.6', 'Roofline model', 'Achievable performance = min(peak compute, bandwidth × arithmetic intensity).'),
  c('t2-2.6', 'MFU', 'Model FLOPs utilisation: achieved model FLOPs/sec ÷ hardware peak.'),
  c('t2-2.6', 'Kernel fusion', 'Combining several ops into one GPU kernel so intermediate results never leave on-chip memory.'),
  c('t2-2.6', 'bf16', '16-bit float with fp32\'s exponent range (8 bits) but less precision. Standard for training without loss scaling.'),
  c('t2-2.7', 'Prefill vs decode', 'Prefill processes the prompt in parallel (compute-heavy); decode generates one token at a time (memory-bound).'),
  c('t2-2.7', 'TTFT', 'Time to first token: latency until the first output token. Dominated by queueing + prefill.'),
  c('t2-2.7', 'Continuous batching', 'Scheduling at the iteration level: sequences join and leave the running batch every step.'),
  c('t2-2.7', 'PagedAttention', 'Store the KV cache in fixed-size blocks (like OS pages) to avoid fragmentation and allow sharing.'),
  c('t2-2.7', 'Speculative decoding', 'A draft model proposes k tokens; the target model verifies them in one pass, giving the same output distribution faster.'),
  c('t2-2.7', 'AWQ / GPTQ', 'Post-training weight quantisation methods (often 4-bit) that keep accuracy by protecting important weights or correcting errors.'),
  c('t2-2.8', 'All-reduce', 'A collective operation where every GPU ends up with the sum (or mean) of all GPUs\' tensors. Used to sync gradients.'),
  c('t2-2.8', 'ZeRO / FSDP', 'Shard optimizer states (stage 1), gradients (2) and parameters (3) across data-parallel GPUs.'),
  c('t2-2.8', 'Tensor parallelism', 'Split individual weight matrices across GPUs; needs fast interconnect (NVLink).'),
  c('t2-2.8', 'Pipeline parallelism', 'Split layers into stages on different GPUs, with micro-batches flowing through to reduce idle "bubbles".'),
  c('t2-2.8', 'Activation checkpointing', 'Drop activations in the forward pass and recompute them during backward, trading compute for memory.'),
  c('t2-2.10', 'DCGM exporter', 'NVIDIA tool exposing GPU metrics (utilisation, memory, temperature, XID errors) to Prometheus.'),
  c('t2-2.10', 'KEDA', 'Kubernetes event-driven autoscaling: scale workloads on external metrics such as queue length.'),
  c('t2-2.10', 'Taints & tolerations', 'Taints repel pods from nodes (e.g. GPU nodes); only pods with matching tolerations can schedule there.'),

  c('t3-3.1', 'Bias–variance tradeoff', 'Error = bias² + variance + noise. Simple models underfit (bias); complex ones overfit (variance).'),
  c('t3-3.1', 'MAP estimation', 'Maximise likelihood × prior. A Gaussian prior gives L2 regularisation.'),
  c('t3-3.1', 'Double descent', 'Test error rises near the interpolation threshold, then falls again as models grow even larger.'),
  c('t3-3.2', 'Chinchilla scaling', 'Compute-optimal: scale parameters and tokens together, roughly 20 tokens per parameter.'),
  c('t3-3.2', 'μP', 'A parametrisation under which optimal hyperparameters transfer from small to large widths.'),
  c('t3-3.2', 'Grokking', 'Delayed generalisation: test accuracy jumps long after training accuracy reached 100%.'),
  c('t3-3.4', 'Policy gradient', '∇J(θ) = E[∇log π_θ(a|s) · A(s,a)]. Push up the probability of actions with positive advantage.'),
  c('t3-3.4', 'Advantage', 'A(s,a) = Q(s,a) − V(s): how much better an action is than average in that state.'),
  c('t3-3.4', 'PPO', 'Policy optimisation with a clipped probability ratio that keeps updates small and stable.'),
  c('t3-3.5', 'GRPO', 'Group Relative Policy Optimization: sample a group of answers per prompt and use within-group normalised rewards as advantages. No value model.'),
  c('t3-3.5', 'Reward hacking', 'The policy exploits flaws in the reward signal instead of achieving the intended goal.'),
  c('t3-3.5', 'RLVR', 'RL with verifiable rewards: rewards come from automatic checkers (unit tests, math answers).'),
  c('t3-3.6', 'Residual stream', 'The running vector each layer reads from and writes to. A shared communication channel inside the transformer.'),
  c('t3-3.6', 'Induction head', 'An attention head that completes patterns: after "A B … A", it predicts "B".'),
  c('t3-3.6', 'Superposition', 'Representing more features than dimensions using nearly orthogonal directions, which causes polysemantic neurons.'),
  c('t3-3.6', 'Activation patching', 'Replace an activation with its value from another input to test whether that component causally matters.'),

  c('math-1', 'Dot product', 'a·b = Σ aᵢbᵢ = ‖a‖‖b‖cos θ. It measures alignment.'),
  c('math-1', 'Softmax', 'softmax(x)ᵢ = e^{xᵢ} / Σⱼ e^{xⱼ}. Turns logits into a probability distribution.'),
  c('math-1', 'Standard error', 'σ/√n: the uncertainty of a sample mean.'),
  c('math-2', 'Cross-entropy', 'H(p,q) = −Σ p log q. As a loss with one-hot targets: −log q(correct class).'),
  c('math-2', 'KL divergence', 'KL(P‖Q) = Σ P log(P/Q) ≥ 0. Asymmetric "extra bits" from using Q in place of P.'),
  c('math-2', 'Entropy', 'H(P) = −Σ P log P. The average uncertainty or surprise of a distribution.'),
  c('math-2', 'MLE', 'Maximum likelihood estimation: pick parameters that make the observed data most probable.'),
  c('math-2', 'Jacobian', 'The matrix of all partial derivatives of a vector function. Its shape follows [outputs × inputs].'),
  c('math-2', 'SVD', 'M = UΣVᵀ. Truncating to the top r singular values gives the best rank-r approximation.'),
  c('math-2', 'Adam update', 'm ← β₁m + (1−β₁)g;  v ← β₂v + (1−β₂)g²;  θ ← θ − η·m̂/(√v̂ + ε)'),
  c('math-3', 'Bootstrap', 'Resample the data with replacement many times to estimate a statistic\'s sampling distribution.'),
  c('math-3', 'Bellman equation', 'V(s) = E[r + γV(s′)]. The value of a state is the immediate reward plus the discounted future value.'),
  c('math-3', 'ELBO', 'Evidence lower bound: E_q[log p(x,z)] − E_q[log q(z)] ≤ log p(x). Maximised in variational inference.'),
]
